### ISSUE TITLE
cannot import name 'afx' from 'moviepy' 

### ISSUE THREAD

**Issue by 5656wwed** [nxNull/DownEdit#70]
## Help Wanted: i dont know how to fix it

[Programs][INFO] Dependencies installed successfully.
[Programs][INFO] Starting the application...
Traceback (most recent call last):
  File "C:\Users\Tlite\Desktop\DownEdit-main\main.py", line 1, in <module>
    from downedit.cli import run
  File "C:\Users\Tlite\Desktop\DownEdit-main\downedit\__init__.py", line 22, in <module>
    from downedit.edit import (
  File "C:\Users\Tlite\Desktop\DownEdit-main\downedit\edit\__init__.py", line 1, in <module>
    from .video._process                    import VideoProcess
  File "C:\Users\Tlite\Desktop\DownEdit-main\downedit\edit\video\__init__.py", line 1, in <module>
    from ._operation import (
  File "C:\Users\Tlite\Desktop\DownEdit-main\downedit\edit\video\_operation.py", line 5, in <module>
    from ._editor import VideoEditor
  File "C:\Users\Tlite\Desktop\DownEdit-main\downedit\edit\video\_editor.py", line 1, in <module>
    from moviepy import (
ImportError: cannot import name 'afx' from 'moviepy' (C:\Users\Tlite\AppData\Roaming\Python\Python312\site-packages\moviepy\__init__.py)
[Programs][INFO] Done! Exiting...

---

Thank you for taking the time to help!

**Comment by sokunheng** [comment]
Hello @5656wwed Let's try again

**Comment by sokunheng** [comment]
Hello @5656wwed is everything okay?
